export const consts = {
  imagemPoke: document.querySelector(".imagem-poke"),
  pokemonSobre: document.querySelector(".pokemon-sobre"),
  nomePokemon: document.querySelector(".modal-title"),
  modalOverlay: document.querySelector(".modal-overlay"),
  fecharButton: document.querySelector(".modal-close-button"),
  containerSvg: document.querySelector(".container-svg"),
  peso: document.querySelector(".peso"),
  altura: document.querySelector(".altura"),
  hpDiv: document.querySelector(".hp"),
  attackDiv: document.querySelector(".attack"),
  dfDiv: document.querySelector(".defense"),
  spAtkDiv: document.querySelector(".spc-atk"),
  SpdefDiv: document.querySelector(".sp-def"),
  speedDiv: document.querySelector(".speed"),
  mensagem1: document.querySelector(".mensagem-poke1"),
  mensagem2: document.querySelector(".mensagem-poke2"),
  mensagem3: document.querySelector(".mensagem-poke3"),
  mensagem4: document.querySelector(".mensagem-poke4"),
  mensagem5: document.querySelector(".mensagem-poke5"),
  mensagem6: document.querySelector(".mensagem-poke6"),
  containerPoke: document.querySelector(".container-poke"),
  statusContainer: document.querySelector(".status-container"),
  abilityName: document.querySelector(".habilidades-name"),
  btnTop: document.querySelector(".btn-top"),
  form: document.querySelector(".container-input"),

  h2Container: document.querySelector(".h2-container"),
  typeContainer: document.querySelector(".container-types"),
  containerBack: document.querySelector(".container-back"),
  pokedex: document.querySelector('[data-js="Pokedex"]'),
  imgSearch: document.querySelector(".img-search"),
  containerSearch: document.querySelector(".container-search"),
  windowImgPoke: document.querySelector(".img-windowPokemon"),
  windowAbout: document.querySelector(".window-about"),
  windowWeight: document.querySelector(".weight-pokemonScreen"),
  windowheight: document.querySelector(".height-pokemonScreen"),
  spanWindowHeight: document.querySelector(".alturaScreen"),
  spanWindowWeight: document.querySelector(".pesoScreen"),
  windowScreenTypes: document.querySelector(".window-types"),
  windowInformationPokemon: document.querySelector(
    ".window-informationPokemon"
  ),
  fetchdata: [],
  result: null,
  currentPage: 1,
  PokeThatIWillSearch: null,
  containerErro: document.querySelector(".catch-erro"),
  quadradoErro: document.querySelector(".catch-quadrado"),
};

export const constsAfterSearchPoke = {
  spanHp: document.createElement("span"),
  spanAtk: document.createElement("span"),
  spanDef: document.createElement("span"),
  spanSpatk: document.createElement("span"),
  spanSpDef: document.createElement("span"),
  spanSpeed: document.createElement("span"),
  mensagemLoading1: document.querySelector(".mensagem-loading1"),
  mensagemLoading2: document.querySelector(".mensagem-loading2"),
  mensagemLoading3: document.querySelector(".mensagem-loading3"),
  mensagemLoading4: document.querySelector(".mensagem-loading4"),
  mensagemLoading5: document.querySelector(".mensagem-loading5"),
  mensagemLoading6: document.querySelector(".mensagem-loading6"),
  attackDiv: document.querySelector(".loading-attack"),
  dfDiv: document.querySelector(".loading-defense"),
  spAtkDiv: document.querySelector(".loading-spc-atk"),
  SpdefDiv: document.querySelector(".loading-sp-def"),
  speedDiv: document.querySelector(".loading-speed"),
  hpDiv: document.querySelector(".loading-hp"),
};
export const constDoCards = {
  spanHp: document.createElement("span"),
  spanAtk: document.createElement("span"),
  spanDef: document.createElement("span"),
  spanSpatk: document.createElement("span"),
  spanSpDef: document.createElement("span"),
  spanSpeed: document.createElement("span"),
  typesDiv: document.createElement("div"),
  newTitulo: document.createElement("h2"),
};
